### ISSUE TITLE
[Bug] IntroWidget disappears after some browser resize events

### ISSUE THREAD

**Issue by ghost** [conterra/mapapps-introjs#1]
While using the [Demo Site](https://www.mapapps.de/mapapps/resources/apps/downloads_introjs/index.html?lang=en) , I noticed that after some browser resize events, e.g. 
- using the windows+ cursor-left keys, 
- using the device toolbar in chrome dev. tools,
  the widget disappears. 
  This behaviour only occurs, if the user did not push the 'start intro' button - so only for the welcome screen.

Tested browsers: Chrome 53.0, Edge 25.1

**Comment by matthiasstein** [comment]
This is a default map.apps behavior. Everytime the template changes, all widgets will be closed.
