### ISSUE TITLE
Intro-Window will open again and again if it is only closed by the X-Button

### ISSUE THREAD

**Issue by mischagiese** [conterra/mapapps-introjs#2]
The Intro-Window appears again and again, even if the box for "Beim nächsten Start nicht mehr anzeigen" is checked and the window is closed with the X-Button.
The introduction must therefore be started at least once, before the window no longer apperas.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-introjs/releases/tag/v1.0.5

**Comment by HubertusKolster** [comment]
we installed dn_introjs 1.0.5 .  the checkbox  "Beim nächsten Start nicht mehr anzeigen" works only in a browser session. If I close the browser and open it again, the tool apears again.  Did the checkbox use a cookie to store the result?
