### ISSUE TITLE
Intro-Window will open again after browser is closed and open again

### ISSUE THREAD

**Issue by HubertusKolster** [conterra/mapapps-introjs#3]
we installed dn_introjs 1.0.5 . the checkbox "Beim nächsten Start nicht mehr anzeigen" works only in a browser session. If I close the browser and open it again, the tool apears again. Did the checkbox use a cookie to store the result?

**Comment by matthiasstein** [comment]
Yes, you're right. There was a problem during the creation of this cookie. This is fixed in [https://github.com/conterra/mapapps-introjs/releases/tag/1.0.6](https://github.com/conterra/mapapps-introjs/releases/tag/1.0.6)
